export interface NoteTemplate {
  id: string
  label: string
  hint: string
  title: string
  content: string
}

export const NOTE_TEMPLATES: NoteTemplate[] = [
  {
    id: 'blank',
    label: 'Em branco',
    hint: 'Só o título',
    title: 'Nova nota',
    content: '',
  },
  {
    id: 'place',
    label: 'Lugar',
    hint: 'Cidade, floresta, masmorra…',
    title: 'Novo lugar',
    content: [
      '## Resumo',
      '',
      '',
      '## Quem vive aqui',
      '',
      '- ',
      '',
      '## Rumores',
      '',
      '- [ ] ',
      '',
      '## Ligado a',
      '',
      '- [[',
    ].join('\n'),
  },
  {
    id: 'npc',
    label: 'NPC',
    hint: 'Aparência, voz, motivação',
    title: 'Novo NPC',
    content: [
      '## Aparência e voz',
      '',
      '',
      '## O que quer',
      '',
      '',
      '## Segredo',
      '',
      '',
      '## Onde encontrar',
      '',
      '[[',
    ].join('\n'),
  },
  {
    id: 'faction',
    label: 'Facção',
    hint: 'Reino, guilda, culto…',
    title: 'Nova facção',
    content: [
      '## Liderança',
      '',
      '- [[',
      '',
      '## Objetivos',
      '',
      '- ',
      '',
      '## Recursos',
      '',
      '| Recurso | Quem controla |',
      '| --- | --- |',
      '|  |  |',
      '',
      '## Território',
      '',
      '[[',
    ].join('\n'),
  },
  {
    id: 'session',
    label: 'Sessão',
    hint: 'Recap e cenas da mesa',
    title: 'Nova sessão',
    content: [
      '## Recap',
      '',
      '',
      '## Cenas',
      '',
      '- [ ] ',
      '',
      '## NPCs em cena',
      '',
      '- [[',
      '',
      '## Tesouro e ganchos',
      '',
      '| Item | De onde | Destino |',
      '| --- | --- | --- |',
      '|  |  |  |',
    ].join('\n'),
  },
]
